name: Generate Index
on:
  push:
    paths:
      - 'machines/**'
jobs:
  build-index:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build machines index
        run: |
          python3 - <<'PY'
          import os, pathlib, sys
          root = pathlib.Path("machines")
          out = ["# Machines index\n"]
          if root.exists():
              for d in sorted([p for p in root.iterdir() if p.is_dir()]):
                  name = d.name
                  readme = d / "README.md"
                  title = name
                  if readme.exists():
                      first = open(readme).read().splitlines()
                      if first:
                          title = first[0].lstrip('# ').strip()
                  out.append(f"- [{title}](machines/{name}/README.md)")
          open("MACHINE_INDEX.md","w").write("\\n".join(out))
          print("Generated MACHINE_INDEX.md")
      - name: Commit index
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add MACHINE_INDEX.md || true
          git commit -m "ci: regenerate machine index" || true
          git push || true
