#!/usr/bin/env python3
"""
Convert a PDF into a Markdown writeup and extract embedded images.

- Extracts embedded images from each page (if any).
- Renders each page to a PNG (saved as images/page-<n>-render.png) so you always have images.
- If pytesseract is available and a page has little text, it will OCR the rendered page.
- Produces machines/<difficulty>/<machine>/README.md referencing raw-logs/<pdf> and images/*

Usage:
  python3 tools/convert_pdf_to_md.py machines/Medium/Imagery/raw-logs/manual.pdf

Dependencies:
  pip install PyMuPDF pillow pytesseract
  sudo apt install -y tesseract-ocr  # optional, for OCR
"""
import sys
import os
from pathlib import Path
import textwrap

try:
    import fitz  # PyMuPDF
except Exception as e:
    print("Missing PyMuPDF (fitz). Install with: pip install PyMuPDF", file=sys.stderr)
    raise

from PIL import Image
import io

try:
    import pytesseract
    OCR_AVAILABLE = True
except Exception:
    OCR_AVAILABLE = False

def ensure_dirs(base_dir: Path):
    images_dir = base_dir / "images"
    raw_dir = base_dir / "raw-logs"
    images_dir.mkdir(parents=True, exist_ok=True)
    raw_dir.mkdir(parents=True, exist_ok=True)
    return images_dir, raw_dir

def extract_embedded_images(doc, page, images_dir: Path, page_no: int):
    saved = []
    images = page.get_images(full=True)
    for img_index, img in enumerate(images, start=1):
        xref = img[0]
        try:
            pix = fitz.Pixmap(doc, xref)
            # Convert CMYK or other to RGB if needed
            if pix.n > 4:
                pix = fitz.Pixmap(fitz.csRGB, pix)
            out_name = f"page-{page_no}-img-{img_index}.png"
            out_path = images_dir / out_name
            pix.save(str(out_path))
            pix = None
            saved.append(str(Path("images") / out_name))
        except Exception as ex:
            # fallback: skip this image but continue
            print(f"Warning: failed to extract embedded image page {page_no} img {img_index}: {ex}", file=sys.stderr)
    return saved

def render_page_to_image(page, images_dir: Path, page_no: int, zoom=2):
    mat = fitz.Matrix(zoom, zoom)
    pix = page.get_pixmap(matrix=mat, alpha=False)
    mode = "RGB"
    img = Image.frombytes(mode, [pix.width, pix.height], pix.samples)
    out_name = f"page-{page_no}-render.png"
    out_path = images_dir / out_name
    img.save(out_path)
    return str(Path("images") / out_name), img

def ocr_image(img):
    if not OCR_AVAILABLE:
        return ""
    try:
        return pytesseract.image_to_string(img)
    except Exception as e:
        print("OCR failed:", e, file=sys.stderr)
        return ""

def extract_text_from_pdf(pdf_path: Path, images_dir: Path):
    doc = fitz.open(pdf_path)
    pages = []
    for i, page in enumerate(doc, start=1):
        text = page.get_text("text").strip()
        embedded = extract_embedded_images(doc, page, images_dir, i)
        # always render page to an image (ensures images/ not empty)
        rendered_relpath, pil_img = render_page_to_image(page, images_dir, i)
        if (not text or len(text) < 40) and OCR_AVAILABLE:
            ocr_text = ocr_image(pil_img).strip()
            if ocr_text:
                # combine OCR result with any extracted text
                text = (text + "\n\n" + ocr_text).strip()
        pages.append((i, text, embedded + [rendered_relpath]))
    return pages

def build_markdown(machine_name: str, pdf_filename: str, pages):
    header = f"# {machine_name}\n\n"
    md = header
    md += f"**Source PDF:** `raw-logs/{pdf_filename}`\n\n"
    # TL;DR from first non-empty text
    tldr = ""
    for (_, text, _) in pages:
        if text:
            first_lines = [l.strip() for l in text.splitlines() if l.strip()][:3]
            if first_lines:
                tldr = " ".join(first_lines)[:400]
                break
    if tldr:
        md += f"## TL;DR\n\n{tldr}\n\n"
    md += "## Extracted walkthrough\n\n"
    for (pnum, text, images) in pages:
        md += f"### Page {pnum}\n\n"
        if text:
            md += "```\n" + textwrap.dedent(text).strip() + "\n```\n\n"
        else:
            md += "_No text extracted from this page._\n\n"
        for img in images:
            md += f"![page-{pnum}]({img})\n\n"
    md += "\n---\n\n"
    md += "Generated by tools/convert_pdf_to_md.py — review & redact sensitive info before publishing.\n"
    return md

def main():
    if len(sys.argv) < 2:
        print("Usage: python tools/convert_pdf_to_md.py path/to/machines/<Difficulty>/<Machine>/raw-logs/file.pdf", file=sys.stderr)
        sys.exit(1)
    pdf_path = Path(sys.argv[1])
    if not pdf_path.exists():
        print("PDF not found:", pdf_path, file=sys.stderr)
        sys.exit(1)
    # Expect path like machines/Medium/Imagery/raw-logs/manual.pdf
    machine_dir = pdf_path.parent.parent  # .../raw-logs/ -> machine dir
    machine_name = machine_dir.name
    images_dir, raw_dir = ensure_dirs(machine_dir)
    pages = extract_text_from_pdf(pdf_path, images_dir)
    md = build_markdown(machine_name, pdf_path.name, pages)
    out_readme = machine_dir / "README.md"
    out_readme.write_text(md, encoding="utf-8")
    print("Wrote", out_readme)
    imgs = sorted([p.name for p in images_dir.glob("*")])
    print("Extracted images:", imgs)

if __name__ == "__main__":
    main()
